[package]
edition = "2021"
name = "guilible"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.7.0"
once_cell = "1.20.3"
online-statistics = "0.2.6"
pollster = "0.4.0"
pyo3 = "0.23.5"
wgpu = "24.0.1"
winit = "0.30.9"
